POPPLER_PATH = ""
TESSERACT_PATH = ""
LOGO_PATH = ""
CONTACT_EMAIL = "brandon@godevservices.com"
DOWNLOAD_LINK = "https://pdfflow.godevservices.com"
TELEMETRY_URL = "https://telemetry.pdf-flow.brandongorman.me/telemetry"