name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli

    # Package for Windows
    - name: Install win32com (for Windows build)
      run: pip install pywin32

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .

    - name: Deploy Windows to S3
      run: |
        aws s3 cp "dist/windows/PDF Flow.exe" "s3://pdf-flow/PDF Flow.exe"

    # Package for Linux
    - name: PyInstaller Linux
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: .

    - name: List Linux Build Artifacts
      run: |
        ls dist/linux/

    - name: Deploy Linux to S3
      run: |
        aws s3 cp "dist/linux/PDF Flow" "s3://pdf-flow/PDF FLow"
